create table if not exists public.inventory (
  product text primary key,
  stock_qty integer not null check (stock_qty >= 0),
  price_inr numeric(10,2) not null check (price_inr >= 0),
  cost_inr numeric(10,2) not null check (cost_inr >= 0),
  qr_code text unique,
  category text,
  size text,
  color text,
  reorder_level integer not null default 0 check (reorder_level >= 0),
  updated_by uuid,
  updated_at timestamptz not null default now()
);

alter table public.inventory add column if not exists qr_code text;
alter table public.inventory add column if not exists category text;
alter table public.inventory add column if not exists size text;
alter table public.inventory add column if not exists color text;
alter table public.inventory add column if not exists reorder_level integer not null default 0;
alter table public.inventory add column if not exists updated_by uuid;
alter table public.inventory add column if not exists updated_at timestamptz not null default now();

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  sold_at date not null,
  product text not null references public.inventory(product) on update cascade,
  quantity integer not null check (quantity > 0),
  price_inr numeric(10,2) not null check (price_inr >= 0),
  cost_inr numeric(10,2) not null check (cost_inr >= 0),
  status text not null default 'completed' check (status in ('completed', 'returned')),
  payment_type text default 'cash',
  customer_name text,
  customer_phone text,
  created_at timestamptz not null default now()
);

alter table public.sales add column if not exists status text not null default 'completed';
alter table public.sales add column if not exists payment_type text default 'cash';
alter table public.sales add column if not exists customer_name text;
alter table public.sales add column if not exists customer_phone text;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'sales_status_check'
  ) then
    alter table public.sales
    add constraint sales_status_check check (status in ('completed', 'returned'));
  end if;
end
$$;

create table if not exists public.returns (
  id bigint generated by default as identity primary key,
  sale_id bigint not null references public.sales(id) on delete cascade,
  product text not null,
  quantity integer not null check (quantity > 0),
  return_date date not null,
  reason text,
  refund_amount numeric(10,2) not null check (refund_amount >= 0),
  created_by uuid,
  created_at timestamptz not null default now()
);

create table if not exists public.operation_logs (
  id bigint generated by default as identity primary key,
  action text not null,
  entity_name text not null,
  metadata jsonb,
  created_by uuid,
  created_at timestamptz not null default now()
);

create table if not exists public.app_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text not null check (role in ('admin', 'staff')) default 'staff',
  created_at timestamptz not null default now()
);

create unique index if not exists inventory_qr_code_key on public.inventory(qr_code) where qr_code is not null;

insert into public.inventory (product, stock_qty, price_inr, cost_inr, qr_code, category, size, color, reorder_level)
values
  ('Classic T-Shirt', 50, 699, 320, 'SKU-TSHIRT-001', 'Tops', 'M', 'Black', 10),
  ('Denim Jacket', 20, 2499, 1500, 'SKU-JACKET-001', 'Outerwear', 'L', 'Blue', 5),
  ('Summer Dress', 25, 1799, 980, 'SKU-DRESS-001', 'Dresses', 'M', 'Red', 8),
  ('Hoodie', 18, 1499, 820, 'SKU-HOODIE-001', 'Outerwear', 'XL', 'Grey', 6),
  ('Jeans', 30, 1999, 1150, 'SKU-JEANS-001', 'Bottoms', '32', 'Navy', 7)
on conflict (product) do update set
  stock_qty = excluded.stock_qty,
  price_inr = excluded.price_inr,
  cost_inr = excluded.cost_inr,
  qr_code = excluded.qr_code,
  category = excluded.category,
  size = excluded.size,
  color = excluded.color,
  reorder_level = excluded.reorder_level,
  updated_at = now();

create or replace function public.current_app_role()
returns text
language sql
stable
as $$
  select case
    when auth.uid() is null then 'admin'
    else coalesce((select role from public.app_users where user_id = auth.uid()), 'staff')
  end;
$$;

create or replace function public.log_operation(
  p_action text,
  p_entity_name text,
  p_metadata jsonb
)
returns void
language sql
as $$
  insert into public.operation_logs(action, entity_name, metadata, created_by)
  values (p_action, p_entity_name, p_metadata, auth.uid());
$$;

create or replace function public.place_order(
  p_sold_at date,
  p_product text,
  p_quantity integer
)
returns void
language plpgsql
as $$
declare
  v_stock integer;
  v_price numeric(10,2);
  v_cost numeric(10,2);
begin
  if p_quantity <= 0 then
    raise exception 'Quantity must be greater than 0';
  end if;

  select stock_qty, price_inr, cost_inr
  into v_stock, v_price, v_cost
  from public.inventory
  where product = p_product
  for update;

  if not found then
    raise exception 'Product not found in inventory';
  end if;
  if v_stock < p_quantity then
    raise exception 'Out of Stock';
  end if;

  update public.inventory
  set stock_qty = stock_qty - p_quantity,
      updated_by = auth.uid(),
      updated_at = now()
  where product = p_product;

  insert into public.sales(sold_at, product, quantity, price_inr, cost_inr, status)
  values (p_sold_at, p_product, p_quantity, v_price, v_cost, 'completed');

  perform public.log_operation('place_order', p_product, jsonb_build_object('quantity', p_quantity));
end;
$$;

create or replace function public.process_return(
  p_sale_id bigint,
  p_return_date date,
  p_quantity integer,
  p_reason text default null
)
returns void
language plpgsql
as $$
declare
  v_sale public.sales%rowtype;
  v_refund numeric(10,2);
begin
  if p_quantity <= 0 then
    raise exception 'Return quantity must be greater than 0';
  end if;

  select * into v_sale from public.sales where id = p_sale_id for update;
  if not found then
    raise exception 'Sale record not found';
  end if;
  if v_sale.status = 'returned' then
    raise exception 'Sale already returned';
  end if;
  if p_quantity > v_sale.quantity then
    raise exception 'Return quantity exceeds sold quantity';
  end if;

  v_refund := v_sale.price_inr * p_quantity;

  update public.inventory
  set stock_qty = stock_qty + p_quantity,
      updated_by = auth.uid(),
      updated_at = now()
  where product = v_sale.product;

  update public.sales set status = 'returned' where id = p_sale_id;

  insert into public.returns(sale_id, product, quantity, return_date, reason, refund_amount, created_by)
  values (p_sale_id, v_sale.product, p_quantity, p_return_date, p_reason, v_refund, auth.uid());

  perform public.log_operation('process_return', v_sale.product, jsonb_build_object('sale_id', p_sale_id, 'quantity', p_quantity));
end;
$$;

create or replace function public.delete_sale_and_restore_stock(
  p_sale_id bigint
)
returns void
language plpgsql
as $$
declare
  v_product text;
  v_quantity integer;
begin
  if public.current_app_role() <> 'admin' then
    raise exception 'Admin only action';
  end if;

  select product, quantity into v_product, v_quantity from public.sales where id = p_sale_id for update;
  if not found then
    raise exception 'Sale record not found';
  end if;

  update public.inventory
  set stock_qty = stock_qty + v_quantity,
      updated_by = auth.uid(),
      updated_at = now()
  where product = v_product;

  delete from public.sales where id = p_sale_id;

  perform public.log_operation('delete_sale', v_product, jsonb_build_object('sale_id', p_sale_id));
end;
$$;

alter table public.inventory enable row level security;
alter table public.sales enable row level security;
alter table public.returns enable row level security;
alter table public.app_users enable row level security;
alter table public.operation_logs enable row level security;

drop policy if exists inventory_read_policy on public.inventory;
create policy inventory_read_policy on public.inventory for select using (true);

drop policy if exists inventory_write_policy on public.inventory;
create policy inventory_write_policy on public.inventory for all
using (public.current_app_role() = 'admin')
with check (public.current_app_role() = 'admin');

drop policy if exists sales_read_policy on public.sales;
create policy sales_read_policy on public.sales for select using (true);

drop policy if exists sales_insert_policy on public.sales;
create policy sales_insert_policy on public.sales for insert with check (true);

drop policy if exists sales_update_policy on public.sales;
create policy sales_update_policy on public.sales
for update
using (true)
with check (true);

drop policy if exists returns_read_policy on public.returns;
create policy returns_read_policy on public.returns for select using (true);

drop policy if exists returns_insert_policy on public.returns;
create policy returns_insert_policy on public.returns for insert with check (true);

drop policy if exists app_users_read_policy on public.app_users;
create policy app_users_read_policy on public.app_users for select using (auth.uid() = user_id or public.current_app_role() = 'admin');

drop policy if exists operation_logs_read_policy on public.operation_logs;
create policy operation_logs_read_policy on public.operation_logs for select using (true);

drop policy if exists operation_logs_insert_policy on public.operation_logs;
create policy operation_logs_insert_policy on public.operation_logs for insert with check (true);
